### ISSUE TITLE
Contract sub-resource locator doesn't accept mixed-case addresses

### ISSUE THREAD

**Issue by xaviarias** [web3j/web3j-openapi#90]
When using a contract sub-resource locator such as
`https://rinkeby.epirus.io/contracts/0x08ccb6099fccd8c496d07d0da6f1c85d73d7fd2c`
the Jersey server cannot find the resource after the address since the regex pattern is only accepting lower case hex letters:

```kotlin
const val HEX_40_PATTERN = "0x[a-f0-9]{40}"
```

This should be replaced by:

```kotlin
const val HEX_40_PATTERN = "0x[a-fA-F0-9]{40}"
```

**Comment by xaviarias** [comment]
Fixed in master

**Comment by conor10** [comment]
This issue has been mentioned on **Web3 Labs Community**. There might be relevant details there:

https://community.web3labs.com/t/cannot-run-burn-and-name-methods-on-new-contract/91/3

**Comment by conor10** [comment]
This issue has been mentioned on **Web3 Labs Community**. There might be relevant details there:

https://community.web3labs.com/t/web3j-v4-8-0-released/112/1
