### ISSUE TITLE
Project creation fails

### ISSUE THREAD

**Issue by hedaia-cobalt** [web3j/web3j-openapi#95]
`epirus new helloworld `
Threw an error that the project generation failed and asked to check the logs. However, where the logs can be found 
We need more details please about these common issues

**Comment by SweeXordious** [comment]
Please find the logs in the same directory as you run the command under a file called : `logs`.
Thank you reporting. We will try to include more details about this.

**Comment by SweeXordious** [comment]
Reopen if not solved.
