### ISSUE TITLE
Cannot create openapi from sol8 contracts

### ISSUE THREAD

**Issue by AndyShoeshim** [web3j/web3j-openapi#99]
# Cannot create openapi from sol8 contracts
I cannot use this tool with the contracts created with the new version of solidity.

## Description
I'm trying to create the OpenAPI doc from the contracts i've written used OpenZeppelin standards. They use version of solidity compiler greater than 0.7 and when i try to run the command to create the openapi file, it fails since the compiler used is different from the one that contracts use.

## Enviroment
Windows 10
Solc 8 compiler (contracts created with this type of solidity compiler)

**Comment by SweeXordious** [comment]
Can you please provide some logs? Maybe the smart contract also, etc ?

**Comment by AndyShoeshim** [comment]
I tried the following command since i dont'have a epirus account. Before i start, i think i should explicit the fact that i'm using ERC721 standard.

epirus openapi jar

The i provide the path to the contracts and the build fails

```

> Task :compileSolidity FAILED
Compiler run successful. Artifact(s) can be found in directory build/resources/main/solidity.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileSolidity'.
> java.lang.Exception: No compatible solc release could be found for the file: C:\Users\AndreaScarpiello\.epirus\projects\1269164787\Web3App\src\main\solidity\NFTFactory.sol
```

**Comment by SweeXordious** [comment]
I am able to reproduce. Will look into it. Thanks for letting us know.

**Comment by SweeXordious** [comment]
You will need to update the solidity version to at most `0.8.9` as that's the latest version our current release supports.
I will open an issue stating that we need to cut a new release to support the newer version.
